# Generated by Django 3.2.7 on 2021-09-08 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaInvestiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineaInvestigacion', models.CharField(max_length=60, verbose_name='Línea de Investigación')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tesis',
            name='nombreTesis',
            field=models.CharField(max_length=60, null=True, verbose_name='Nombre de Tesis'),
        ),
        migrations.AddField(
            model_name='tesis',
            name='lineaInvestigacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminApp.lineainvestiacion'),
        ),
    ]
