# Generated by Django 3.2.7 on 2021-09-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20210908_1613'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineaInvestiacion',
            new_name='LineaInvestigacion',
        ),
    ]
