# Generated by Django 3.2.5 on 2021-09-03 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('correoUnitru', models.EmailField(max_length=254, verbose_name='Correo unitru')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorPracticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesorPracticas', models.CharField(max_length=60, verbose_name='Asesor de Prácticas')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AsesorTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asesorTesis', models.CharField(max_length=60, verbose_name='Asesor de Tesis')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facultad', models.CharField(max_length=60, verbose_name='Facultad')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurado', models.CharField(max_length=60, verbose_name='Jurado')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(verbose_name='Fecha inicio')),
                ('fechaFinal', models.DateField(verbose_name='Fecha final')),
                ('planTesis', models.FileField(upload_to='', verbose_name='Plan de Tesis')),
                ('informeFinal', models.FileField(upload_to='', verbose_name='Informe final')),
                ('estadoTesis', models.CharField(default='Revisión', max_length=20, verbose_name='Estado')),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.alumno')),
                ('asesorJurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.jurado')),
                ('asesorTesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.asesortesis')),
            ],
        ),
        migrations.CreateModel(
            name='Practicas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horasPractica', models.IntegerField(verbose_name='Horas')),
                ('lugarPractica', models.CharField(max_length=90, verbose_name='Lugar')),
                ('fechaInicio', models.DateField(verbose_name='Fecha inicio')),
                ('fechaFinal', models.DateField(verbose_name='Fecha final')),
                ('porcentajeAvance', models.CharField(max_length=30, verbose_name='Porcentaje de Avance')),
                ('informePracticas', models.FileField(upload_to='', verbose_name='Informe de Practicas')),
                ('estadoPractica', models.CharField(default='Revisión', max_length=20, verbose_name='Estado')),
                ('estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.alumno')),
                ('asesorPracticas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.asesorpracticas')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(max_length=60, verbose_name='Carrera')),
                ('estado', models.BooleanField(default=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='carreras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.carrera'),
        ),
    ]
