# Generated by Django 3.2.7 on 2021-09-07 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnoApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tesis',
            old_name='asesorJurado',
            new_name='jurado',
        ),
        migrations.AlterField(
            model_name='practicas',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.alumno'),
        ),
        migrations.AlterField(
            model_name='practicas',
            name='informePracticas',
            field=models.FileField(null=True, upload_to='practicas/pdfs/'),
        ),
        migrations.AlterField(
            model_name='practicas',
            name='porcentajeAvance',
            field=models.CharField(max_length=30, null=True, verbose_name='Porcentaje de Avance'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='alumno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alumnoApp.alumno'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='informeFinal',
            field=models.FileField(null=True, upload_to='tesis/pdfs'),
        ),
        migrations.AlterField(
            model_name='tesis',
            name='planTesis',
            field=models.FileField(null=True, upload_to='tesis/pdfs'),
        ),
    ]
