# Generated by Django 3.2.7 on 2021-09-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnoApp', '0002_auto_20210906_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
