# Generated by Django 3.2.7 on 2021-09-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumnoApp', '0003_alumno_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='practicas',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='practicas',
            name='asesorPracticas',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='asesorTesis',
        ),
        migrations.RemoveField(
            model_name='tesis',
            name='jurado',
        ),
        migrations.DeleteModel(
            name='Alumno',
        ),
        migrations.DeleteModel(
            name='AsesorPracticas',
        ),
        migrations.DeleteModel(
            name='AsesorTesis',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Facultad',
        ),
        migrations.DeleteModel(
            name='Jurado',
        ),
        migrations.DeleteModel(
            name='Practicas',
        ),
        migrations.DeleteModel(
            name='Tesis',
        ),
    ]
