# Generated by Django 3.2.5 on 2021-09-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SeguridadApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='bio',
            new_name='rol',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='web',
        ),
    ]
