# Generated by Django 3.2.7 on 2021-09-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SeguridadApp', '0002_auto_20210905_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
